name: "Extraer versión"

outputs:
  version:
    description: "Versión de la app"
    value: "${{steps.version.outputs.version}}"
    
version:
  using: "composite"
  steps:
    - name: "Extraer versión"
      id: version
      shell: bash
      run: |
        version=$(jq -r '.version' ./package.json)
        echo "Image version: $version"
        echo  "version=${version}" >> $GITHUB_OUTPUT

