name: CD
on:
  workflow_call:
  
     inputs:
      environment:
       type: string
       required: true
       
      tag:
       type: string
       required: true
        
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Hacer pull de la imagen de Docker
        run: |
          docker pull ${{ vars.DOCKER_USERNAME }}/${{inputs.tag}}
          
      - name: Desplegar
        run: |
          docker run -d -p 3000:3000  ${{ vars.DOCKER_USERNAME }}/${{inputs.tag}}

      - name: Verificar si el contenedor está corriendo
        run: docker ps

      - name: Verificar respuesta de la app
        run: |
           sleep 30
           curl http://localhost:3000
