name: CD
on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Hacer pull de la imagen de Docker
        run: |
          docker pull ${{ vars.DOCKER_USERNAME }}/mi-app-node:0.0.2
          
      - name: Desplegar
        run: |
          docker run -d -p 3000:3000  ${{ vars.DOCKER_USERNAME }}/mi-app-node:0.0.2

      - name: Verificar si el contenedor está corriendo
        run: docker ps

      - name: Verificar respuesta de la app
        run: |
           sleep 30
           curl http://localhost:3000
